#!/usr/bin/env bash
# installs nginx with apt-get and configur it

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
sudo echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
sudo service nginx restart
