#!/usr/bin/env bash
# Installing HAProxy and configr it:

sudo apt-get install -y haproxy

sudo service haproxy start

sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend elgeo.tech
    timeout client  30000
    bind 0:80
    default_backend elgeo.tech_backend

backend elgeo.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 502876-web-01 54.87.252.218:80 check
    server 502876-web-02 52.204.94.236:80 check
EOT

sudo service haproxy restart

