#!/usr/bin/env bash
# Pings an IP address received as an argument 5 times and if no argument dispaly Usage: 5-is_the_host_on_the_network {IP_ADDRESS}.

if [ $# -eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c 5 "$1"
fi
